Repository department-for-transport-BODS/bods-backend, pull requests merged in 2025-06, with the labels that each got.

#542 release(test): v1.0.168
  VERSION
  docker-compose.yml
  src/boilerplate/common_layer/database/models/__init__.py
  src/boilerplate/common_layer/database/models/model_transmodel.py
  src/boilerplate/common_layer/database/repos/__init__.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/timetables_etl/etl/app/api/__init__.py
  src/timetables_etl/etl/app/api/geometry.py
  src/timetables_etl/etl/app/api/models.py
  src/timetables_etl/etl/app/load/servicepatterns_common.py
  src/timetables_etl/etl/app/load/servicepatterns_distance.py
  src/timetables_etl/etl/app/models.py
  tests/factories/database/transmodel.py
  tests/timetables_etl/etl/api/__init__.py
  tests/timetables_etl/etl/api/test_geometry.py
  tests/timetables_etl/etl/load/test_servicepatterns_distance.py
  tests/timetables_etl/etl/transform/test_service_pattern_tracks.py
  timetables-etl.yaml
Labels: release

#544 release(test): v1.0.169
  VERSION
  src/timetables_etl/etl/app/load/servicepatterns_distance.py
  tests/timetables_etl/etl/load/test_servicepatterns_distance.py
Labels: release

#545 feat(ETLProcess): Enable OSRM API
  VERSION
  src/timetables_etl/etl/app/load/servicepatterns_distance.py
  tests/timetables_etl/etl/load/test_servicepatterns_distance.py
  timetables-etl.yaml
Labels: feat

#548 release(test): v1.0.171
  VERSION
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
  src/timetables_etl/generate_output_zip/app/output_processing.py
Labels: release

#550 fix(ETLProcess): Ignored duplicate code
  src/boilerplate/common_layer/database/models/model_transmodel.py
Labels: fix

#552 fix(ETLProcess): Cleanup once remote dataset file is move to s3
  VERSION
  src/timetables_etl/download_dataset/app/download_dataset.py
Labels: fix

#553 fix(ETLProcess): Cleanup once remote dataset file is move to s3 updated log level
  VERSION
  src/timetables_etl/download_dataset/app/download_dataset.py
Labels: fix

#554 release(test): v1.0.173
  VERSION
  src/timetables_etl/download_dataset/app/download_dataset.py
Labels: release

#555 release(uat): v1.0.173
  VERSION
  src/timetables_etl/download_dataset/app/download_dataset.py
Labels: release

#531 feat(TrackConsolidation): Track consolidation lambda implementation
  periodic-tasks.yaml
  poetry.lock
  pyproject.toml
  src/boilerplate/common_layer/database/models/model_transmodel.py
  src/boilerplate/common_layer/database/repos/repo_common.py
  src/boilerplate/common_layer/database/repos/repo_junction.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/periodic_tasks/consolidate_tracks/app/__init__.py
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  src/periodic_tasks/consolidate_tracks/app/utils.py
  tests/boilerplate/common_layer/database/repos/test_repo_common.py
  tests/boilerplate/common_layer/database/repos/test_repo_junction.py
  tests/boilerplate/common_layer/database/repos/test_repo_naptan.py
  tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
  tests/factories/database/__init__.py
  tests/factories/database/junction.py
  tests/factories/database/transmodel.py
  tests/periodic_tasks/consolidate_tracks/__init__.py
  tests/periodic_tasks/consolidate_tracks/test_consolidate_tracks.py
  tests/periodic_tasks/consolidate_tracks/test_utils.py
Labels: feat

#559 release(test): v1.0.174
  VERSION
  periodic-tasks.yaml
  poetry.lock
  pyproject.toml
  src/boilerplate/common_layer/database/models/model_transmodel.py
  src/boilerplate/common_layer/database/repos/repo_common.py
  src/boilerplate/common_layer/database/repos/repo_junction.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/periodic_tasks/consolidate_tracks/app/__init__.py
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  src/periodic_tasks/consolidate_tracks/app/utils.py
  tests/boilerplate/common_layer/database/repos/test_repo_common.py
  tests/boilerplate/common_layer/database/repos/test_repo_junction.py
  tests/boilerplate/common_layer/database/repos/test_repo_naptan.py
  tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
  tests/factories/database/__init__.py
  tests/factories/database/junction.py
  tests/factories/database/transmodel.py
  tests/periodic_tasks/consolidate_tracks/__init__.py
  tests/periodic_tasks/consolidate_tracks/test_consolidate_tracks.py
  tests/periodic_tasks/consolidate_tracks/test_utils.py
Labels: release

#561 fix(ETLProcess): Fix statemachine definition for skip tracks
  VERSION
  src/timetables_etl.statemachine.json
Labels: fix
