Repository department-for-transport-BODS/bods-backend, pull requests merged in 2025-04, with the labels that each got.

#442 release(test): v1.0.133
  .github/workflows/cleanup-branches.yaml
  .github/workflows/deploy.yml
  .vscode/settings.json
  VERSION
  fares-etl.yaml
  periodic-tasks.yaml
  pyproject.toml
  src/boilerplate/common_layer/database/models/error_codes.py
  src/boilerplate/common_layer/exceptions/__init__.py
  src/boilerplate/common_layer/exceptions/exceptions_download.py
  src/timetables_etl.statemachine.json
  src/timetables_etl/download_dataset/app/file_download.py
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
  src/timetables_etl/generate_output_zip/app/models/model_lambda.py
  tests/timetables_etl/download_dataset/test_download_dataset.py
  tests/timetables_etl/download_dataset/test_file_download.py
  timetables-etl.yaml
  tools/zip_tools/__init__.py
  tools/zip_tools/cli.py
  tools/zip_tools/multi_zip_maker.py
  tools/zip_tools/xml_formatter.py
  tools/zip_tools/zip_repackage.py
Labels: release

#443 release(uat): v1.0.133
  .github/workflows/cleanup-branches.yaml
  .github/workflows/deploy.yml
  .vscode/settings.json
  VERSION
  fares-etl.yaml
  periodic-tasks.yaml
  pyproject.toml
  src/boilerplate/common_layer/database/models/error_codes.py
  src/boilerplate/common_layer/exceptions/__init__.py
  src/boilerplate/common_layer/exceptions/exceptions_download.py
  src/timetables_etl.statemachine.json
  src/timetables_etl/download_dataset/app/file_download.py
  src/timetables_etl/etl/app/transform/service_pattern_stops.py
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
  src/timetables_etl/generate_output_zip/app/models/model_lambda.py
  tests/factories/database/transmodel.py
  tests/timetables_etl/download_dataset/test_download_dataset.py
  tests/timetables_etl/download_dataset/test_file_download.py
  tests/timetables_etl/etl/transform/test_service_pattern_stops.py
  timetables-etl.yaml
  tools/zip_tools/__init__.py
  tools/zip_tools/cli.py
  tools/zip_tools/multi_zip_maker.py
  tools/zip_tools/xml_formatter.py
  tools/zip_tools/zip_repackage.py
Labels: release

#444 fix(ExceptionHandler): Exception handling improvements
  VERSION
  src/timetables_etl.statemachine.json
  src/timetables_etl/exception_handler/app/exception_handler.py
  src/timetables_etl/exception_handler/app/models.py
  tests/timetables_etl/exception_handler/test_exception_handler.py
Labels: fix

#449 fix(DownloadDataset): Make remote filename for S3 unique when downloading from URL + increase memory allocation
  src/timetables_etl/download_dataset/app/download_dataset.py
  tests/timetables_etl/download_dataset/test_download_dataset.py
  timetables-etl.yaml
Labels: fix

#451 chore(CI): Re-integrate main
  .github/workflows/deploy.yml
  VERSION
  src/timetables_etl/download_dataset/app/download_dataset.py
  tests/timetables_etl/download_dataset/test_download_dataset.py
  timetables-etl.yaml
Labels: chore

#452 release(dev): v1.0.135
  VERSION
Labels: release

#455 fix(ExceptionHandler): Add missing data to exception handler log
  VERSION
  src/timetables_etl.statemachine.json
  src/timetables_etl/exception_handler/app/exception_handler.py
Labels: fix

#456 fix(Fares): Implement semaphores
  fares-etl.yaml
  src/fares_etl.statemachine.json
Labels: fix

#459 release(dev): v1.0.137
  VERSION
Labels: release

#460 release(test): v1.0.137
  .github/workflows/deploy.yml
  VERSION
  fares-etl.yaml
  src/fares_etl.statemachine.json
  src/timetables_etl.statemachine.json
  src/timetables_etl/download_dataset/app/download_dataset.py
  src/timetables_etl/exception_handler/app/exception_handler.py
  src/timetables_etl/exception_handler/app/models.py
  tests/timetables_etl/download_dataset/test_download_dataset.py
  tests/timetables_etl/exception_handler/test_exception_handler.py
  timetables-etl.yaml
Labels: release

#461 fix(Fares): Fix fares initialize pipeline payload
  VERSION
  src/fares_etl.statemachine.json
Labels: fix

#463 chore(test): DQS Trigger
  VERSION
  src/timetables_etl.statemachine.json
Labels: chore

#465 fix: add BatchGetItem permissions to get naptan stop ids for fares
  fares-etl.yaml
Labels: fix

#466 chore: bump version
  VERSION
Labels: chore

#467 feat(ClamAV): Add Option to Skip ClamAV Step
  VERSION
  src/common_lambdas/clamav_scanner/app/clamav_scanner.py
  src/common_lambdas/clamav_scanner/app/models.py
  src/timetables_etl.statemachine.json
Labels: feat

#468 feat(timetables-etl): Use performETLOnly variable to skip Schema Checks and PTI
  VERSION
  src/timetables_etl.statemachine.json
Labels: feat

#469 fix(timetables-sm): Add $ to performETLOnly in ClamAV step
  VERSION
  src/timetables_etl.statemachine.json
Labels: fix

#470 fix(timetables-sm): Remap the StateMachine Variables
  VERSION
  src/timetables_etl.statemachine.json
Labels: fix

#471 fix(DQSTrigger): Revert change to trigger
  VERSION
  src/timetables_etl.statemachine.json
Labels: fix

#472 style(tools): Fix linting issues
  tools/common/db_tools.py
  tools/download_dataset/cli.py
  tools/file_viewer/checks/__init__.py
  tools/file_viewer/checks/tab_checks.py
  tools/file_viewer/txc/__init__.py
  tools/file_viewer/txc/app_txc.py
  tools/file_viewer/txc/checks/__init__.py
  tools/file_viewer/txc/checks/duplicate_journeys.py
  tools/file_viewer/txc/tabs/__init__.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/__init__.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps_tables.py
  tools/file_viewer/txc/tabs/routes/__init__.py
  tools/file_viewer/txc/tabs/routes/tab_routes.py
  tools/file_viewer/txc/tabs/routes/tab_routes_tables.py
  tools/file_viewer/txc/tabs/services/__init__.py
  tools/file_viewer/txc/tabs/services/tab_service.py
  tools/file_viewer/txc/tabs/vehicle_journeys/__init__.py
  tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys.py
  tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys_tables.py
  tools/file_viewer/txc/utils_stoppoints.py
  tools/file_viewer/txc/utils_tables.py
  tools/initialize_pipeline/cli.py
  tools/local_etl/mock_task_data.py
  tools/post_schema_check/cli.py
  tools/profiler/cli.py
  tools/schema_check/cli.py
Labels: style

#473 refactor(txc-parser): Fix linting issues
  src/boilerplate/common_layer/xml/txc/parser/services_flexible.py
  src/boilerplate/common_layer/xml/txc/parser/stop_points/parse_stop_point_types.py
Labels: refactor

#464 fix(GenerateOutputZip): Populate missing revision metadata fields
  src/boilerplate/common_layer/database/dataclasses/__init__.py
  src/boilerplate/common_layer/database/dataclasses/stats.py
  src/boilerplate/common_layer/database/repos/repo_organisation.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/boilerplate/common_layer/database/repos/utils.py
  src/timetables_etl/generate_output_zip/app/etl_revision_stats.py
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
  tests/boilerplate/common_layer/database/repos/test_repo_organization.py
  tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
Labels: fix

#476 fix(ExceptionHandler): Fix parent exception handler args
  VERSION
  src/timetables_etl.statemachine.json
Labels: fix

#477 release(test): v1.0.146
  VERSION
  fares-etl.yaml
  src/boilerplate/common_layer/database/dataclasses/__init__.py
  src/boilerplate/common_layer/database/dataclasses/stats.py
  src/boilerplate/common_layer/database/repos/repo_organisation.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/boilerplate/common_layer/database/repos/utils.py
  src/boilerplate/common_layer/xml/txc/parser/services_flexible.py
  src/boilerplate/common_layer/xml/txc/parser/stop_points/parse_stop_point_types.py
  src/common_lambdas/clamav_scanner/app/clamav_scanner.py
  src/common_lambdas/clamav_scanner/app/models.py
  src/timetables_etl.statemachine.json
  src/timetables_etl/generate_output_zip/app/etl_revision_stats.py
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
  tests/boilerplate/common_layer/database/repos/test_repo_organization.py
  tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
  tools/common/db_tools.py
  tools/download_dataset/cli.py
  tools/file_viewer/checks/__init__.py
  tools/file_viewer/checks/tab_checks.py
  tools/file_viewer/txc/__init__.py
  tools/file_viewer/txc/app_txc.py
  tools/file_viewer/txc/checks/__init__.py
  tools/file_viewer/txc/checks/duplicate_journeys.py
  tools/file_viewer/txc/tabs/__init__.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/__init__.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps_tables.py
  tools/file_viewer/txc/tabs/routes/__init__.py
  tools/file_viewer/txc/tabs/routes/tab_routes.py
  tools/file_viewer/txc/tabs/routes/tab_routes_tables.py
  tools/file_viewer/txc/tabs/services/__init__.py
  tools/file_viewer/txc/tabs/services/tab_service.py
  tools/file_viewer/txc/tabs/vehicle_journeys/__init__.py
  tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys.py
  tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys_tables.py
  tools/file_viewer/txc/utils_stoppoints.py
  tools/file_viewer/txc/utils_tables.py
  tools/initialize_pipeline/cli.py
  tools/local_etl/mock_task_data.py
  tools/post_schema_check/cli.py
  tools/profiler/cli.py
  tools/schema_check/cli.py
Labels: release

#481 fix(sam): Increase lambda memory to avoid Out of Memory crashes
  VERSION
  fares-etl.yaml
  timetables-etl.yaml
Labels: fix

#482 release(test): v1.0.147
  .github/workflows/lint-pr.yaml
  VERSION
  fares-etl.yaml
  src/boilerplate/common_layer/database/client.py
  src/boilerplate/common_layer/database/repos/repo_fares.py
  timetables-etl.yaml
  tools/db_viewer/cli.py
  tools/db_viewer/fares.py
  tools/db_viewer/naptan.py
  tools/db_viewer/organisation.py
  tools/db_viewer/timetables.py
Labels: release

#483 refactor(fares): add extra logs to the fares lambdas
  VERSION
  src/boilerplate/common_layer/db/constants.py
  src/boilerplate/common_layer/xml/netex/helpers/__init__.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_fare_products.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_tariff.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_zones.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_resource_frame.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_service_frame.py
  src/fares_etl/etl/app/etl_process.py
  src/fares_etl/etl/app/load/metadata.py
  src/fares_etl/etl/app/transform/data_catalogue.py
  src/fares_etl/etl/app/transform/metadata.py
  src/fares_etl/metadata_aggregation/app/load/dataset.py
  src/fares_etl/metadata_aggregation/app/load/metadata.py
  src/fares_etl/metadata_aggregation/app/load/violations.py
  src/fares_etl/metadata_aggregation/app/metadata_aggregation.py
  src/fares_etl/metadata_aggregation/app/transform/transform_metadata.py
Labels: refactor

#484 fix(netex-parser): Parse timestamps without timezone as UTC
  VERSION
  src/boilerplate/common_layer/xml/netex/parser/netex_utility.py
  tests/fares_etl/etl/transform/test_metadata.py
  tests/xml/netex/conftest.py
  tests/xml/netex/fare_frame/test_netex_fare_tariff.py
  tests/xml/netex/test_netex_utility.py
  tests/xml/netex/test_scheduled_stop_point_ref.py
Labels: fix, test

#486 refactor(netex-etl): add logging of naptan stop ids and their discrepancies
  VERSION
  src/fares_etl/etl/app/transform/metadata.py
  src/fares_etl/metadata_aggregation/app/transform/transform_metadata.py
Labels: refactor

#488 ci(dev2): Removed references to dev2 in code for decommissioning
  .github/workflows/build.yml
  VERSION
  samconfig.yaml
  src/boilerplate/common_layer/database/client.py
Labels: ci

#487 fix(fares-aggregation): Calculate unique counts for User Profiles, Trip and Pass products
  VERSION
  src/fares_etl/metadata_aggregation/app/metadata_aggregation.py
  src/fares_etl/metadata_aggregation/app/transform/transform_metadata.py
  tests/fares_etl/metadata_aggregation/transform/test_transform_metadata.py
Labels: fix

#489 fix(netex-parser): assume Europe/London instead of UTC for timestamps without Timezone
  VERSION
  src/boilerplate/common_layer/xml/netex/parser/netex_utility.py
  tests/xml/netex/test_netex_utility.py
Labels: fix

#490 release(test): v1.0.152
  .github/workflows/build.yml
  VERSION
  samconfig.yaml
  src/boilerplate/common_layer/database/client.py
  src/boilerplate/common_layer/db/constants.py
  src/boilerplate/common_layer/xml/netex/helpers/__init__.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_fare_products.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_tariff.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_zones.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_resource_frame.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_service_frame.py
  src/boilerplate/common_layer/xml/netex/parser/netex_utility.py
  src/fares_etl/etl/app/etl_process.py
  src/fares_etl/etl/app/load/metadata.py
  src/fares_etl/etl/app/transform/data_catalogue.py
  src/fares_etl/etl/app/transform/metadata.py
  src/fares_etl/metadata_aggregation/app/load/dataset.py
  src/fares_etl/metadata_aggregation/app/load/metadata.py
  src/fares_etl/metadata_aggregation/app/load/violations.py
  src/fares_etl/metadata_aggregation/app/metadata_aggregation.py
  src/fares_etl/metadata_aggregation/app/transform/transform_metadata.py
  tests/fares_etl/etl/transform/test_metadata.py
  tests/fares_etl/metadata_aggregation/transform/test_transform_metadata.py
  tests/xml/conftest.py
  tests/xml/netex/conftest.py
  tests/xml/netex/fare_frame/test_netex_fare_tariff.py
  tests/xml/netex/test_netex_utility.py
  tests/xml/netex/test_scheduled_stop_point_ref.py
  tests/xml/txc/parser/test_txc_serviced_organisation.py
  tests/xml/txc/parser/txc_journey_pattern_section/test_txc_journey_pattern_section.py
  tests/xml/txc/parser/txc_journey_pattern_section/test_txc_journey_pattern_timing_link.py
  tests/xml/txc/parser/txc_route_section/test_txc_route_section.py
  tests/xml/txc/parser/txc_route_section/test_txc_route_section_location.py
  tests/xml/txc/parser/txc_service/test_txc_service_journey_pattern.py
  tests/xml/txc/parser/txc_service/test_txc_service_line.py
  tests/xml/txc/parser/txc_service/test_txc_service_line_description.py
  tests/xml/txc/parser/txc_service/test_txc_service_standard_service.py
  tests/xml/txc/parser/txc_vehicle_journey/operating_profile/test_txc_operating_profile_periodic_days.py
  tests/xml/txc/parser/txc_vehicle_journey/test_txc_vehicle_journeys.py
  tests/xml/txc/parser/txc_vehicle_journey/test_txc_vehicle_journeys_flexible.py
  tests/xml/txc/parser/txc_vehicle_journey/test_txc_vehicle_journeys_timing_links.py
Labels: release

#492 feat(etl-timetables): populate organisation_datasetrevision_localities and organisation_datasetrevision_admin_areas
  VERSION
  src/boilerplate/common_layer/database/models/__init__.py
  src/boilerplate/common_layer/database/models/model_junction.py
  src/boilerplate/common_layer/database/repos/__init__.py
  src/boilerplate/common_layer/database/repos/repo_junction.py
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
Labels: feat

#493 release(test): v1.0.153
  VERSION
  src/boilerplate/common_layer/database/models/__init__.py
  src/boilerplate/common_layer/database/models/model_junction.py
  src/boilerplate/common_layer/database/repos/__init__.py
  src/boilerplate/common_layer/database/repos/repo_junction.py
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
Labels: release

#497 fix(netex-parser): Parse PublicationRefreshInterval as ISO 8601 duration
  VERSION
  src/boilerplate/common_layer/xml/netex/parser/netex_publication_delivery.py
  src/boilerplate/common_layer/xml/utils/__init__.py
  src/boilerplate/common_layer/xml/utils/xml_duration.py
  src/timetables_etl/etl/app/transform/service_pattern_stops_durations.py
  tests/timetables_etl/etl/transform/test_service_pattern_stops_time.py
  tests/xml/utils/test_xml_duration.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps.py
  tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys.py
Labels: fix

#498 fix(NaptanCacheStateMachine): Update naptan population schedule + add retries
  VERSION
  periodic-tasks.yaml
Labels: fix

#499 release(test): v1.0.155
  VERSION
  periodic-tasks.yaml
  src/boilerplate/common_layer/xml/netex/parser/netex_publication_delivery.py
  src/boilerplate/common_layer/xml/utils/__init__.py
  src/boilerplate/common_layer/xml/utils/xml_duration.py
  src/timetables_etl/etl/app/transform/service_pattern_stops_durations.py
  tests/timetables_etl/etl/transform/test_service_pattern_stops_time.py
  tests/xml/utils/test_xml_duration.py
  tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps.py
  tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys.py
Labels: release

#501 ci(UAT2): Reenable deployments against UAT2
  .github/workflows/deploy.yml
Labels: ci

#505 ci(UAT2): Re-enable deployments against UAT2 (#504)
  VERSION
Labels: ci
