Repository department-for-transport-BODS/bods-backend, pull requests merged in 2025-08, with the labels that each got.

#608 release(test): v1.0.187
  VERSION
  periodic-tasks.yaml
Labels: release

#547 fix(ETLProcess): Add parsing for easting and northing coordinates for Tracks
  VERSION
  src/boilerplate/common_layer/utils_location.py
  src/boilerplate/common_layer/xml/txc/parser/route_sections.py
  tests/xml/txc/parser/txc_route_section/test_txc_route_section_location.py
Labels: fix

#617 feat(ETLProcess): Revert - Added send email method for the email notification
  fares-etl.yaml
  poetry.lock
  pyproject.toml
  samconfig.yaml
  src/boilerplate/common_layer/database/exceptions/__init__.py
  src/boilerplate/common_layer/database/exceptions/exceptions_db.py
  src/boilerplate/common_layer/database/models/error_codes.py
  src/boilerplate/common_layer/database/repos/__init__.py
  src/boilerplate/common_layer/database/repos/repo_user.py
  src/boilerplate/common_layer/exceptions/exception_email.py
  src/boilerplate/common_layer/notification/__init__.py
  src/boilerplate/common_layer/notification/base.py
  src/boilerplate/common_layer/notification/emails.py
  src/boilerplate/common_layer/notification/govuk_notify.py
  src/boilerplate/common_layer/notification/interface.py
  src/boilerplate/common_layer/notification/local_time.py
  src/boilerplate/common_layer/utils.py
  src/fares_etl/metadata_aggregation/app/metadata_aggregation.py
  src/timetables_etl/collate_files/app/collate_files.py
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
  template.yaml
  timetables-etl.yaml
  tools/email/__init__.py
  tools/email/cli.py
Labels: feat

#623 release(test): v1.0.190
  VERSION
  src/boilerplate/common_layer/utils_location.py
  src/boilerplate/common_layer/xml/txc/parser/route_sections.py
  tests/xml/txc/parser/txc_route_section/test_txc_route_section_location.py
Labels: release
