Repository department-for-transport-BODS/bods-backend, pull requests merged in 2025-05, with the labels that each got.

#508 release(test): v1.0.157
  VERSION
  src/boilerplate/common_layer/exceptions/exceptions_fares.py
  src/fares_etl/metadata_aggregation/app/metadata_aggregation.py
  src/fares_etl/validation/app/fares_validator.py
  src/fares_etl/validation/app/schema/schema.json
  src/fares_etl/validation/app/types.py
Labels: release

#514 chore: use secrets manager for db username
  VERSION
  fares-etl.yaml
  periodic-tasks.yaml
  timetables-etl.yaml
Labels: chore

#513 release(test): v1.0.159
  VERSION
  fares-etl.yaml
  periodic-tasks.yaml
  src/boilerplate/common_layer/xml/netex/helpers/__init__.py
  src/boilerplate/common_layer/xml/netex/helpers/helpers_counts.py
  src/boilerplate/common_layer/xml/netex/models/data_objects/netex_frame_service.py
  src/boilerplate/common_layer/xml/netex/models/fare_frame/netex_frame_fare.py
  src/boilerplate/common_layer/xml/netex/parser/data_objects/netex_frame_service.py
  src/boilerplate/common_layer/xml/netex/parser/fare_frame/netex_frame_fare.py
  src/fares_etl/etl/app/transform/metadata.py
  tests/fares_etl/etl/transform/test_metadata.py
  tests/fares_etl/test_data/netex1.xml
  tests/fares_etl/test_data/netex2.xml
  timetables-etl.yaml
Labels: release

#516 chore: increase fares map concurrency to 250
  VERSION
  src/fares_etl.statemachine.json
Labels: chore

#517 release(test): v1.0.160
  VERSION
  src/fares_etl.statemachine.json
Labels: release

#509 refactor(ASM): Updated secret ARN for datadog to reflect changes
  fares-etl.yaml
  periodic-tasks.yaml
  timetables-etl.yaml
Labels: refactor

#522 fix(PerformanceTuning): Memory and concurrency tuning
  VERSION
  src/timetables_etl.statemachine.json
  timetables-etl.yaml
Labels: chore, fix

#524 fix(DatadogApiKey): No requirement for !Sub function when retrieving key
  VERSION
  fares-etl.yaml
  periodic-tasks.yaml
  timetables-etl.yaml
Labels: fix

#525 refactor(UAT2): Removed references and files relating to UAT2
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  samconfig.yaml
  src/boilerplate/common_layer/database/client.py
Labels: refactor
