Repository department-for-transport-BODS/bods-backend, pull requests merged in 2025-07, with the labels that each got.

#569 release(UAT): v1.0.177
  VERSION
  src/timetables_etl/etl/app/load/__init__.py
  src/timetables_etl/etl/app/load/service_pattern_tracks.py
  src/timetables_etl/etl/app/load/servicepatterns_common.py
  src/timetables_etl/etl/app/load/tracks.py
  src/timetables_etl/etl/app/pipeline.py
  src/timetables_etl/etl/app/transform/service_pattern_tracks.py
  tests/timetables_etl/etl/transform/test_service_pattern_tracks.py
Labels: release

#570 fix(PTI): Normalizing modification_datetime by removing microseconds.
  VERSION
  src/boilerplate/common_layer/dynamodb/models.py
Labels: fix

#571 fix(ApiKey): Version bump
  VERSION
Labels: fix

#574 fix(TrackConsolidation): Add batching by stop point pairs
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
  tests/periodic_tasks/consolidate_tracks/test_consolidate_tracks.py
Labels: fix

#577 release(dev): v1.0.180
  VERSION
Labels: release

#575 release(test): v1.0.180
  VERSION
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
  tests/periodic_tasks/consolidate_tracks/test_consolidate_tracks.py
Labels: release, fix

#566 fix(ETLProcess): Resolved 1 level folder issue for zip file creation
  VERSION
  src/timetables_etl/generate_output_zip/app/output_processing.py
Labels: fix

#579 fix(ETLProcess): Trimmed error message
  VERSION
  src/timetables_etl/generate_output_zip/app/output_processing.py
Labels: fix

#583 release(test): Trimmed error message (#579)
  VERSION
  src/timetables_etl/generate_output_zip/app/output_processing.py
Labels: release

#582 release(UAT): v1.0.181
  VERSION
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  src/timetables_etl/generate_output_zip/app/output_processing.py
  tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
  tests/periodic_tasks/consolidate_tracks/test_consolidate_tracks.py
Labels: release

#584 fix(GenerateOutput): Skip zip file creation if there are no successful files
  VERSION
  src/timetables_etl/generate_output_zip/app/generate_output_zip.py
Labels: fix

#591 release(Test): v1.0.184 Consolidate tracks into test
  VERSION
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
Labels: release

#592 fix(ConsolidateTracks): Modify query to use CTE and reduce batch size
  VERSION
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
Labels: fix

#595 feat(TrackConsolidation): Parallelize track consolidation
  periodic-tasks.yaml
  poetry.lock
  pyproject.toml
  src/boilerplate/common_layer/database/repos/repo_junction.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/consolidate_tracks.statemachine.json
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  src/periodic_tasks/consolidate_tracks_batcher/__init__.py
  src/periodic_tasks/consolidate_tracks_batcher/app/__init__.py
  src/periodic_tasks/consolidate_tracks_batcher/app/handler_consolidate_tracks_batcher.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/__init__.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/app/__init__.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/app/handler_consolidate_tracks_stat_reporter.py
  src/periodic_tasks/consolidate_tracks_updater/__init__.py
  src/periodic_tasks/consolidate_tracks_updater/app/__init__.py
  src/periodic_tasks/consolidate_tracks_updater/app/handler_consolidate_tracks_updater.py
  src/periodic_tasks/consolidate_tracks_updater/app/utils.py
  tests/boilerplate/common_layer/database/repos/test_repo_junction.py
  tests/boilerplate/common_layer/s3/__init__.py
  tests/periodic_tasks/consolidate_tracks_updater/test_consolidate_tracks_updater.py
  tests/periodic_tasks/consolidate_tracks_updater/test_utils.py
Labels: feat

#596 release(dev): v1.0.185
  VERSION
Labels: release

#597 release(test): v1.0.185
  VERSION
  periodic-tasks.yaml
  poetry.lock
  pyproject.toml
  src/boilerplate/common_layer/database/repos/repo_junction.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/consolidate_tracks.statemachine.json
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  src/periodic_tasks/consolidate_tracks_batcher/__init__.py
  src/periodic_tasks/consolidate_tracks_batcher/app/__init__.py
  src/periodic_tasks/consolidate_tracks_batcher/app/handler_consolidate_tracks_batcher.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/__init__.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/app/__init__.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/app/handler_consolidate_tracks_stat_reporter.py
  src/periodic_tasks/consolidate_tracks_updater/__init__.py
  src/periodic_tasks/consolidate_tracks_updater/app/__init__.py
  src/periodic_tasks/consolidate_tracks_updater/app/handler_consolidate_tracks_updater.py
  src/periodic_tasks/consolidate_tracks_updater/app/utils.py
  tests/boilerplate/common_layer/database/repos/test_repo_junction.py
  tests/boilerplate/common_layer/s3/__init__.py
  tests/periodic_tasks/consolidate_tracks_updater/test_consolidate_tracks_updater.py
  tests/periodic_tasks/consolidate_tracks_updater/test_utils.py
Labels: release

#601 release(UAT): v1.0.185
  VERSION
  periodic-tasks.yaml
  poetry.lock
  pyproject.toml
  src/boilerplate/common_layer/database/repos/repo_junction.py
  src/boilerplate/common_layer/database/repos/repo_transmodel.py
  src/consolidate_tracks.statemachine.json
  src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
  src/periodic_tasks/consolidate_tracks_batcher/__init__.py
  src/periodic_tasks/consolidate_tracks_batcher/app/__init__.py
  src/periodic_tasks/consolidate_tracks_batcher/app/handler_consolidate_tracks_batcher.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/__init__.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/app/__init__.py
  src/periodic_tasks/consolidate_tracks_stat_reporter/app/handler_consolidate_tracks_stat_reporter.py
  src/periodic_tasks/consolidate_tracks_updater/__init__.py
  src/periodic_tasks/consolidate_tracks_updater/app/__init__.py
  src/periodic_tasks/consolidate_tracks_updater/app/handler_consolidate_tracks_updater.py
  src/periodic_tasks/consolidate_tracks_updater/app/utils.py
  tests/boilerplate/common_layer/database/repos/test_repo_junction.py
  tests/boilerplate/common_layer/s3/__init__.py
  tests/periodic_tasks/consolidate_tracks_updater/test_consolidate_tracks_updater.py
  tests/periodic_tasks/consolidate_tracks_updater/test_utils.py
Labels: release

#603 release(test): v1.0.186
  VERSION
  periodic-tasks.yaml
Labels: release

#604 release(UAT): v1.0.186
  VERSION
  periodic-tasks.yaml
Labels: release
